const etfData = [
    {
      name: "Invesco QQQ Trust",
      displayedSymbol: "QQQ",
      symbol: "QQQ",
      description: "Un fonds indiciel qui suit l'indice NASDAQ-100, composé des 100 plus grandes entreprises non financières cotées au NASDAQ.",
    },
    {
      name: "SPDR S&P 500 ETF Trust",
      displayedSymbol: "SPY",
      symbol: "SPY",
      description: "Un fonds indiciel qui réplique la performance de l'indice S&P 500, représentant 500 grandes entreprises américaines.",
    },
    {
      name: "iShares MSCI France ETF",
      displayedSymbol: "EWQ",
      symbol: "EWQ",
      description: "Un fonds indiciel qui offre une exposition aux actions françaises, reflétant étroitement l'indice CAC 40.",
    },
    {
      name: "iShares MSCI ACWI ETF",
      displayedSymbol: "ACWI",
      symbol: "ACWI",
      description: "Un fonds indiciel qui offre une exposition mondiale aux actions en suivant l'indice MSCI All Country World Index, incluant des entreprises de grande et moyenne capitalisation dans les marchés développés et émergents.",
    },
    {
      name: "iShares China Large-Cap ETF",
      displayedSymbol: "FXI",
      symbol: "FXI",
      description: "Un fonds indiciel qui se concentre sur les grandes entreprises chinoises, principalement celles cotées à la Bourse de Hong Kong.",
    },
    {
      name: "iShares MSCI All Country Asia ex Japan ETF",
      displayedSymbol: "AAXJ",
      symbol: "AAXJ",
      description: "Un fonds indiciel qui offre une exposition à un large éventail de marchés asiatiques, à l'exclusion du Japon.",
    },
    {
      name: "iShares MSCI South Africa ETF",
      displayedSymbol: "EZA",
      symbol: "EZA",
      description: "Un fonds indiciel qui cible les actions sud-africaines, offrant un accès au marché africain.",
    },
    {
      name: "Vanguard Total Stock Market ETF",
      displayedSymbol: "VTI",
      symbol: "VTI",
      description: "Un fonds indiciel qui offre une exposition large au marché américain, couvrant l'ensemble du marché boursier américain.",
    },
    {
      name: "iShares Latin America 40 ETF",
      displayedSymbol: "ILF",
      symbol: "ILF",
      description: "Un fonds indiciel qui offre une exposition à 40 grandes entreprises d'Amérique latine, incluant le Brésil, le Mexique, le Chili et d'autres pays.",
    },
    {
      name: "iShares MSCI Emerging Markets ETF",
      displayedSymbol: "EEM",
      symbol: "EEM",
      description: "Un fonds indiciel qui offre une exposition aux grandes et moyennes entreprises des marchés émergents, incluant la Chine, l'Inde, le Brésil et d'autres économies en développement.",
    },
    {
      name: "iShares MSCI Japan ETF",
      displayedSymbol: "EWJ",
      symbol: "EWJ",
      description: "Un fonds indiciel qui offre une exposition aux actions japonaises, représentant l'une des plus grandes économies développées d'Asie.",
    },
    {
      name: "Vanguard FTSE Europe ETF",
      displayedSymbol: "VGK",
      symbol: "VGK",
      description: "Un fonds indiciel qui offre une exposition large aux actions européennes, couvrant les principales économies du continent.",
    },
    {
      name: "Technology Select Sector SPDR Fund",
      displayedSymbol: "XLK",
      symbol: "XLK",
      description: "Un fonds indiciel qui se concentre sur le secteur technologique, incluant les entreprises de logiciels, matériel informatique et services technologiques.",
    },
    {
      name: "Health Care Select Sector SPDR Fund",
      displayedSymbol: "XLV",
      symbol: "XLV",
      description: "Un fonds indiciel qui offre une exposition au secteur de la santé, incluant les entreprises pharmaceutiques, biotechnologiques et de dispositifs médicaux.",
    },
    {
      name: "Energy Select Sector SPDR Fund",
      displayedSymbol: "XLE",
      symbol: "XLE",
      description: "Un fonds indiciel qui se concentre sur le secteur de l'énergie, incluant les entreprises pétrolières, gazières et de services énergétiques.",
    },
    {
      name: "Vanguard Small-Cap ETF",
      displayedSymbol: "VB",
      symbol: "VB",
      description: "Un fonds indiciel qui offre une exposition aux petites capitalisations américaines, représentant les entreprises de plus petite taille mais à fort potentiel de croissance.",
    },
    {
      name: "SPDR Gold Trust",
      displayedSymbol: "GLD",
      symbol: "GLD",
      description: "Un fonds indiciel qui suit le prix de l'or, offrant une exposition à ce métal précieux souvent utilisé comme valeur refuge et protection contre l'inflation.",
    },
    {
      name: "Vanguard Total Bond Market ETF",
      displayedSymbol: "BND",
      symbol: "BND",
      description: "Un fonds indiciel qui offre une exposition au marché obligataire américain, fournissant des revenus réguliers et une diversification par rapport aux actions.",
    },
    {
      name: "iShares MSCI India ETF",
      displayedSymbol: "INDA",
      symbol: "INDA",
      description: "Un fonds indiciel qui offre une exposition aux actions indiennes, représentant l'une des plus grandes économies émergentes au monde.",
    },
    {
      name: "iShares MSCI Germany ETF",
      displayedSymbol: "EWG",
      symbol: "EWG",
      description: "Un fonds indiciel qui offre une exposition aux actions allemandes, représentant la plus grande économie d'Europe.",
    },
    {
      name: "iShares MSCI United Kingdom ETF",
      displayedSymbol: "EWU",
      symbol: "EWU",
      description: "Un fonds indiciel qui offre une exposition aux actions britanniques, représentant l'une des principales économies européennes.",
    },
  ];

